site_name: VATPRC Docs
site_url: https://docs.vatprc.net/
repo_url: https://github.com/VATPRChina/vatprc-docs
repo_name: VATPRChina/vatprc-docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
